----------------------------------------------------------------- SEQUENCES
CREATE SEQUENCE SPM_SEQ_PEDIDO INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE SPM_SEQ_PRODUCTO INCREMENT BY 1 START WITH 1;

---------------------------------------------------------------- TABLES
CREATE TABLE SPM_PRODUCTO
(
   ID_PRODUCTO   NUMBER NOT NULL,
   NOMBRE        VARCHAR2(500),
   PRIMARY KEY (ID_PRODUCTO)
);

CREATE TABLE SPM_ORDEN
(
   ID_PEDIDO     NUMBER NOT NULL,
   ID_PRODUCTO   NUMBER NOT NULL,
   PRIMARY KEY (ID_PEDIDO, ID_PRODUCTO)
);

CREATE TABLE SPM_PEDIDO
(
   ID_PEDIDO     NUMBER NOT NULL,
   DESCRIPCION   VARCHAR2(500),
   FECHA         DATE,
   PRIMARY KEY (ID_PEDIDO)
);

---------------------------------------------------------------- CONSTRAINTS
ALTER TABLE SPM_ORDEN ADD CONSTRAINT FK_SPM_ORDEN_ID_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES SPM_PEDIDO (ID_PEDIDO);

ALTER TABLE SPM_ORDEN ADD CONSTRAINT FK_SPM_ORDEN_ID_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES SPM_PRODUCTO (ID_PRODUCTO);

---------------------------------------------------------------- GRANTS SEQUENCES 
GRANT SELECT ON SPM_SEQ_PEDIDO TO AUT;

GRANT SELECT ON SPM_SEQ_PRODUCTO TO AUT;

---------------------------------------------------------------- GRANTS TABLES 
GRANT SELECT, INSERT, UPDATE, DELETE ON SPM_PRODUCTO TO AUT;

GRANT SELECT, INSERT, UPDATE, DELETE ON SPM_ORDEN TO AUT;

GRANT SELECT, INSERT, UPDATE, DELETE ON SPM_PEDIDO TO AUT;

